EventEmitter2/EventEmitter2

- lib/eventemitter2.js
- test/simple/removeListener.js
I added a test case for #116 and rebased it.
> Fix removeListener when _events might not exist yet

- README.md
I clarified and expanded the documentation in the project's README file.
As the first line of documentation for the project, it's important to
have a clear and complete README file.
Amoung various minor expansions and clarifications, I added
documentation for the hidden feature of multi-level wildcards (wildcards
that match over multiple levels of namespaces, defined with a
double asterisk). This is a feature that as best I can tell isn't
documented anywhere (at least not anywhere obvious), and the lack of
accessible documentation of the feature seems to cause some grief. (For
example, see issue #154. It's not that the requested feature doesn't
exist, it's that the documentation is strangely silent about this
feature.)
> Update and expand the README

- README.md
- lib/eventemitter2.js
Whenever a listener is removed, a `removeListener` event is emitted with the event type and a reference to the listener.
As well, when a listener is removed through `offAny`, a `removeListenerAny` event is emitted with a reference to the function that was removed.
Fixes #97
> Adds removeListener and removeListenerAny events

- lib/eventemitter2.js
- test/perf/steadyEmmiting.js
Hi there. We actively use EventEmitter2 as part of tinyhook distributed event emitter. We have really big projects on it and start facing issues with performance. On this project we have dedicated process that hosts only one instance of tinyhook (extension of eventemitter2) and its sole purpose is dispatching (emitting of events). Load is really huge, close to dozens of thousands of messages per second and CPU load is also huge.
Based on our investigation we discovered that some part can be optimized in EventEmitter2 code and this merge request has optimized version of emit and emitAsync methods. There is no functional changes introduced, behaviour is exactly the same. 
To proof the improvement we create bench /test/perf/steadyEmitting.js. It shows 25 to 70% improvement. 
Optimized: …
> Fine tune emit performance to make it 1.25-1.7x faster

- test/simple/emit.js
The return value of the `eventEmitter.emit` method of an EventEmitter2 instance that supports wildcard events isn't `true` anymore since EventEmitter2@1.0.1.
Something in this pr must have gone wrong: https://github.com/asyncly/EventEmitter2/pull/163 
I've added some tests for that functionality.
Here's the regression bug that appears since v1.0.1:
```js
var emitter = new EventEmitter2({ verbose: true, wildcard: true });
emitter.on('foo', function () {})
console.log(emitter.emit('foo', 'bar'))
// -> false
```
> Add tests for wildcard emit return value

- lib/eventemitter2.js
- test/simple/addListener.js
To conform to the Node EventEmitter interface: https://nodejs.org/api/events.html\#events_emitter_listenercount_eventname
Fixes https://github.com/asyncly/EventEmitter2/issues/182
> Add listenerCount method

- eventemitter2.d.ts
it resolves error in AOT: ``Error encountered resolving symbol values statically``
the breaking change is instead of using ``EventEmitter2.emitter`` to define event instance type, just simply use ``EventEmitter2``
> make typing compatible with angular2 AOT

- README.md
- eventemitter2.d.ts
- lib/eventemitter2.js
- test/simple/eventNames.js
- test/simple/prepend.js
- test/simple/reconfigure.js
Implements the node 6 functions:
- `prependListener`
- `prependOnceListener`
- `eventNames`
It also adds similar `prepend` methods that are specific to this library:
- `prependMany`
- `prependAny`
There are tests, documentation and typescript defs.
**note**
- I moved the `maxListeners` property of the `_events` object. This seemed like bad design to mix this with event names (e.g. when someone actually wants to have a `maxListeners` event).
- The `eventNames` function is not fully compatible with the node implementation. That's because the node implementation uses `Reflect.keys` instead of `Object.keys`. The former has not so much browser support and since you guys don't have any transpiler infrastructure, I chose to use `Object.keys` instead for the time being.
Fixes: …
> Implement node 6 features

- eventemitter2.d.ts
The typings for `listeners` and `listenersAny` are incorrect. At the very least, they require parentheses to enclose the return type's function signature. However, this PR goes further and uses the declared `Listener` signature.
Closes #217.
> Correct listeners and listenersAny typings

- lib/eventemitter2.js
#207 accidentally broke the removeListener function.
- Renamed the `this.removeListener` boolean to be `this._removeListener`. Same for `this.newListener`
> Fix breaking changes from #207

- lib/eventemitter2.js
- package.json
- test/simple/removeListener.js
Ran into a problem when we were passing `undefined` to `removeAllListeners` and assumed it would ignore this argument.
> Updated removeAllListeners to check for `undefined` rather than `arguments.length`

- test/perf/benchmark.js
Fixes #229 
Output:
```
$ node ./test/perf/benchmark.js 
EventEmitterHeatUp x 3,519,153 ops/sec ±1.12% (88 runs sampled)
EventEmitter x 3,555,339 ops/sec ±1.32% (93 runs sampled)
EventEmitter2 x 10,933,903 ops/sec ±1.21% (90 runs sampled)
EventEmitter2 (wild) x 7,525,248 ops/sec ±1.79% (89 runs sampled)
Fastest is EventEmitter2
```
> Fixes #229 by calling map() instead of pluck()

- lib/eventemitter2.js
If an emitter doesn't listen to any events, it shouldn't set up structures for them when `emit()` / `emitAsync()` is called.
This simple optimisation improves performance in my use-case quite a lot. I have a lot of objects that rarely have events listeners installed on them, but they do emit events internally in many places for those who do. This simple addition optimizes for the most common case where they have nothing installed, without breaking any tests.
It even seems to have an impact on the benchmark test:
Before:
```
npm run benchmark
> eventemitter2@5.0.1 benchmark /Users/lehni/Development/Lineto/EventEmitter2
> node test/perf/benchmark.js
EventEmitterHeatUp x 4,592,188 ops/sec ±0.69% (93 runs sampled)
EventEmitter x 4,502,165 ops/sec ±0.87% (93 runs sampled)
EventEmitter2 x …
```
> Prevent _events creation on emit()

- .gitignore
- README.md
- eventemitter2.d.ts
- lib/eventemitter2.js
- package.json
- test/simple/once.js
1) Added an extended version of node's events.once method.
```
var emitter= new EventEmitter2();
var promise= EventEmitter2.once(emitter, 'event', {
timeout: 0,
Promise: Promise, // a custom Promise constructor
overload: false // overload promise cancellation api if exists with library implementation
})
promise.then(function(data){
console.log(data); // [1, 2, 3]
});
// promise.cancel()
emitter.emit('event', 1, 2, 3);
```
2) Added generic internals:
- resolveOptions() to compute & validate an options object
- toCancelablePromise() to make some promise cancellable with timeout & overload options
3) Reworked emitter.waitFor method to use shared internals (saved the previous interface).
4) Added new overloads/shortcuts for the emitter.waitFor method:
- emitter.waitFor(event, [timeout])
- …
> Feature events.once() & reworked emitter.WaitFor()

- CHANGELOG.md
- README.md
- eventemitter2.d.ts
- lib/eventemitter2.js
- package.json
- test/perf/benchmark.js
- test/perf/package.json
- test/simple/addListener.js
- test/simple/emit.js
- test/simple/listenTo.js
- test/simple/symbol.js
- test/wildcardEvents/eventsNames.js
- test/wildcardEvents/normalizeEvent.js
- test/wildcardEvents/removeAllListeners.js
- Symbol events support for simple and wildcard emitters #201
- `emitter.hasListeners` method #251
- `emitter.listenTo` & `emitter.stopListeningTo` methods for listening to an external event emitter of any kind and propagate its events through itself using optional reducers/filters
- async listeners for invoking handlers using setImmediate|setTimeout|nextTick (see `async`, `promisify` and `nextTicks` options for subscription methods)
- Ability for subscription methods to return a listener object to simplify subscription management (see the `objectify` option)
- micro optimizations for performance reasons
- Event name/reference normalization for the `this.event` property #162
- Bug with data arguments for `Any` listeners #254
- `emitter.eventNames` now supports wildcard emitters #214
``` …
```
> Release 6.4.0

- CHANGELOG.md
- README.md
- lib/eventemitter2.js
- test/perf/benchmark.js
- test/simple/emit.js
- test/wildcardEvents/removeAllListeners.js
A bit of simple optimizations for a wildcard emitter, especially for cases when we emitting a simple one level event through wildcard emitter (become almost 4 times faster than before)
before:
> EventEmitter2 x 12,089,852 ops/sec ±4.00% (62 runs sampled)
> **EventEmitter2 (wild) x 167,847 ops/sec ±4.90% (63 runs sampled)**
> EventEmitter2 (wild) using plain events x 190,736 ops/sec ±3.08% (62 runs sampled)
> EventEmitter2 (wild) emitting ns x 676,378 ops/sec ±4.07% (67 runs sampled)
> EventEmitter2 (wild) emitting a plain event x 764,142 ops/sec ±3.87% (71 runs sampled)
> EventEmitter3 x 10,223,124 ops/sec ±3.51% (70 runs sampled)
after:
> Platform: win32, x64, 15267MB
> Node version: v13.11.0
> CPU: 4 x AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx @ 2495MHz
> …
> [Release 6.4.1] Optimized wildcard emitter performance

- CHANGELOG.md
- README.md
- lib/eventemitter2.js
Reworked `makeTypeReducer` internal function (#259);
> [Release 6.4.2] removed eval usage to avoid Content Security Policy issue (#259)

- CHANGELOG.md
- README.md
- lib/eventemitter2.js
- test/waitFor/waitFor.js
Fixes:
- ignoring the `objectify` option in wildcard mode (#265)
- waitFor listeners leakage issue (#262)
> [Release 6.4.3] Fixes #259 waitFor listeners leakage 

- lib/eventemitter2.js
Small change that makes the timeout exception behave similarly to other libraries (e.g Q) by providing an error code on the exception.
> set ETIMEDOUT code on timeout exception

- eventemitter2.d.ts
@RangerMauve turns out this was only a problem on typescript.
Because it didn't have a default export, we had to do
```ts
import { EventEmitter2 } from 'eventemitter2';
```
With the default export declaration, we can just do
```ts
import EventEmitter from 'eventemitter2';
```
This is a breaking change **only** for typescript users.
> Add default export to type definitions. fixes #281
